"use client";

import DynamicChartRenderer from "./DynamicChartRenderer";
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  BarChart3,
  Database,
  Code,
  Save,
  Edit,
  ArrowDownUp,
  Check,
} from "lucide-react";
import { PostgresResponse } from "@/lib/types/DBQueryTypes";
import { DataVisTable } from "./DataVisTable";
import { DataVisQuery } from "./DataVisQuery";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";
import { useState, useMemo, memo, useCallback, useEffect } from "react";
import { useToast } from "@/hooks/use-toast";
import { createClient } from "@/utils/supabase/client";
import { saveChart } from "@/components/stores/chart_store";
import { ChartData } from "@/lib/types/stores/chart";

interface DataVisAgentResultProps {
  chartData: ChartData;
  chartId: string;
  savedCharts?: Array<{ _id: string; title: string; updatedAt: Date }>;
}

// Memoize EmptyState component
const EmptyState = memo(({ message }: { message: string }) => (
  <div className="flex items-center justify-center h-full text-muted-foreground">
    {message}
  </div>
));

// Memoize action buttons
const ActionButtons = memo(
  ({
    onDrill,
    onSave,
    onSaveAndEdit,
    isSaved,
    isAlreadySaved,
  }: {
    onDrill: () => void;
    onSave: () => void;
    onSaveAndEdit: () => void;
    isSaved: boolean;
    isAlreadySaved: boolean;
  }) => (
    <div className="flex flex-wrap justify-between items-center p-4 border-t gap-2">
      <Button variant="outline" className="gap-2" onClick={onDrill}>
        <ArrowDownUp className="h-4 w-4" />
        <span className="hidden sm:inline">Drill Down/Up</span>
        <span className="sm:hidden">Drill</span>
      </Button>

      <div className="flex flex-wrap gap-2">
        {isAlreadySaved ? (
          <Button variant="outline" className="gap-2" disabled>
            <Check className="h-4 w-4" />
            <span className="hidden sm:inline">Saved</span>
            <span className="sm:hidden">Saved</span>
          </Button>
        ) : (
          <Button variant="outline" className="gap-2" onClick={onSave}>
            {isSaved ? (
              <Check className="h-4 w-4" />
            ) : (
              <Save className="h-4 w-4" />
            )}
            <span className="hidden sm:inline">
              {isSaved ? "Saved" : "Save Chart"}
            </span>
            <span className="sm:hidden">{isSaved ? "Saved" : "Save"}</span>
          </Button>
        )}

        <Button variant="default" className="gap-2" onClick={onSaveAndEdit}>
          <Edit className="h-4 w-4" />
          <span className="hidden sm:inline">
            {isAlreadySaved ? "Edit" : "Save & Edit"}
          </span>
          <span className="sm:hidden">Edit</span>
        </Button>
      </div>
    </div>
  )
);

export function DataVisAgentResult({
  chartData,
  chartId,
  savedCharts = [],
}: DataVisAgentResultProps) {
  const [activeTab, setActiveTab] = useState("chart");
  const [isSaved, setIsSaved] = useState(false);
  const router = useRouter();
  const { toast } = useToast();

  // Check if this chart is already saved
  const isAlreadySaved = useMemo(() => {
    return savedCharts.some((chart) => chart._id === chartId);
  }, [chartId, savedCharts]);

  // Set isSaved to true if it's already saved
  useEffect(() => {
    if (isAlreadySaved) {
      setIsSaved(true);
    }
  }, [isAlreadySaved]);

  const { chartJsx, data, query } = chartData;

  // Memoize chart height calculation
  const chartHeight = useMemo(() => {
    // Check for circular charts that need more height
    const isCircularChart =
      chartJsx.includes("<Pie") ||
      chartJsx.includes("<Doughnut") ||
      chartJsx.includes("<PolarArea");

    return isCircularChart ? "h-[500px]" : "h-[400px]";
  }, [chartJsx]);

  // Memoized handler functions
  const handleSave = useCallback(async () => {
    try {
      const supabase = await createClient();
      const { data: userData } = await supabase.auth.getUser();

      if (!userData.user) {
        toast({
          title: "Authentication required",
          description: "Please sign in to save charts",
          variant: "destructive",
        });
        return;
      }

      // Save chart with the ID generated by the agent
      await saveChart(chartData, userData.user.id, "New Chart", chartId);
      setIsSaved(true);

      toast({
        title: "Chart saved",
        description: "Your chart has been saved successfully",
      });
    } catch (error) {
      console.error("Error saving chart:", error);
      toast({
        title: "Failed to save chart",
        description: "There was an error saving your chart",
        variant: "destructive",
      });
    }
  }, [chartData, chartId, toast]);

  const handleSaveAndEdit = useCallback(async () => {
    try {
      if (!isAlreadySaved && !isSaved) {
        await handleSave();
      }
      router.push(`/charts/${chartId}`);
    } catch (error) {
      console.error("Error saving and editing chart:", error);
    }
  }, [handleSave, isSaved, chartId, router, isAlreadySaved]);

  const handleDrill = useCallback(() => {
    console.log("Drilling down/up");
    // Implementation for drill down/up functionality
  }, []);

  return (
    <div className="w-full flex justify-center">
      <Card className="w-full max-w-full md:max-w-[1000px] min-w-0 overflow-hidden">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="w-full border-b rounded-none grid grid-cols-3">
            <TabsTrigger value="chart" className="gap-2">
              <BarChart3 className="h-4 w-4" />
              <span className="truncate">Chart</span>
            </TabsTrigger>
            <TabsTrigger value="data" className="gap-2">
              <Database className="h-4 w-4" />
              <span className="truncate">Data</span>
            </TabsTrigger>
            <TabsTrigger value="query" className="gap-2">
              <Code className="h-4 w-4" />
              <span className="truncate">Query</span>
            </TabsTrigger>
          </TabsList>

          <div className={`relative ${chartHeight}`}>
            <TabsContent
              value="chart"
              className="absolute inset-0 data-[state=inactive]:hidden p-6"
            >
              <DynamicChartRenderer
                jsxString={chartJsx}
                data={data}
                className="w-full h-full"
              />
            </TabsContent>

            <TabsContent
              value="data"
              className="absolute inset-0 data-[state=inactive]:hidden p-6"
            >
              <DataVisTable data={data} />
            </TabsContent>

            <TabsContent
              value="query"
              className="absolute inset-0 data-[state=inactive]:hidden p-6"
            >
              <DataVisQuery query={query} />
            </TabsContent>
          </div>

          <ActionButtons
            onDrill={handleDrill}
            onSave={handleSave}
            onSaveAndEdit={handleSaveAndEdit}
            isSaved={isSaved}
            isAlreadySaved={isAlreadySaved}
          />
        </Tabs>
      </Card>
    </div>
  );
}
